config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/terms", to: "static_pages#terms"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback
  get '/auth/failure', to: 'users#auth_failure', as: :auth_failure

  resources :users do
    member do
      get :following, :followers, :password_edit
      patch :password_edit, to: "users#update_password"
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :photos, only: [:show, :new, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id",
                                  dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token, :activation_token, :reset_token, :password_now
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  validates :user_name, presence: true, length: { maximum: 50 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :password, presence: true, length: { minimum: 8 }, on: :facebook_login

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def feed
    Photo.where("user_id IN(:following_ids)", following_ids: following_ids)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?",
                              current_user.id, id, "follow"])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: "follow"
      )
      notification.save if notification.valid?
    end
  end

  def self.from_omniauth(auth)
    user = User.where('email = ?', auth.info.email).first
    if user.blank?
      user = User.new
    end
    user.uid = auth.uid
    user.username = auth.info.name
    user.email = auth.info.email
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :password_edit, :update_password, :following, :followers]
  before_action :correct_user, only: [:edit, :update, :destroy, :password_edit, :update_password]

  def index
    @search = User.ransack(params[:q])
    @users = @search.result.page(params[:page]).per(30)
  end

  def show
    @user = User.find(params[:id])
    @photos = @user.photos.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def password_edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def update_password
    @user = User.find(params[:id])
    if @user.authenticate(params[:user][:password_now])
      @user.update_attributes(user_params)
      flash.now[:success] = "Password changed"
      render :edit
    else
      flash.now[:danger] = "Failure Password change"
      render :password_edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:info] = "User deleted"
    redirect_to root_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.page(params[:page])
    render "show_follow"
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page])
    render "show_follow"
  end

  def facebook_login
    @user = User.from_omniauth(request.env["omniauth.auth"])
      result = @user.save(context: :facebook_login)
      if result
        log_in @user
        redirect_to @user
      else
        redirect_to auth_failure_path
      end
  end

  def auth_failure
    @user = User.new
    render :new
  end

  private

    def user_params
      params.require(:user).permit(:name, :user_name, :email, :password, :password_confirmation,
                                   :website, :introduce, :phone_number, :gender)
    end

    def correct_password_now?(user)
      user.authenticate(params[:user][:password_now])
    end

    def correct_new_password?
      params[:user][:password] == params[:user][:password_confirmation]
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar rounded-circle")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
  <% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
  <% else %>
  <%= render 'follow' %>
  <% end %>
</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
<%= f.submit "Unfollow", class: "btn btn-secondary" %>
<% end %>

app/views/users/_user.html.erb
  <li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
  </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="row">
  <div class="col mx-auto">
    <div class="card text-center">
      <h1 class="font-italic mt-5">Update your Profile</h1>
      <div class="mr-auto ml-3">
        <%= gravatar_for @user %>
        <a href="http://gravatar.com/emails" target="_blank" rel="nonpener" class="ml-3">
          change
        </a>
      </div>
      <div class=" card-body font-italic">
        <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages", object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :user_name %>
        <%= f.text_field :user_name, class: "form-control" %>

        <%= f.label :website %>
        <%= f.url_field :website, class: "form-control" %>

        <%= f.label :introduce %>
        <%= f.text_area :introduce, class: "form-control mb-5" %>

        <p class="text-left text-muted">private</p>

        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: "form-control" %>

        <%= f.label :gender %>
        <%= f.select :gender, [["", ""], ["male", "male"], ["female", "female"]] %>

        <%= f.submit "Save Change", class: "btn btn-primary font-weight-bolder my-3 w-50" %>
        <% end %>
      </div>
    </div>
    <div class="card text-center mt-4">
      <div class="card-body font-italic">
        <p class="my-auto">
          <%= link_to "Change password", password_edit_user_path(@user),
                                                          class: "btn btn-info font-weight-bolder w-50" %>
        </p>
      </div>
    </div>
    <div class="card text-center mt-4">
      <div class="card-body font-italic">
        <p class="my-auto">
          <%= link_to "Delele Account", @user, method: :delete, data: { confirm: "You Sure?" },
                                                                class: "btn btn-danger font-weight-bolder w-50" %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= paginate @users %>
<%= page_entries_info @users %>

<ul class="users py-5">
  <%= render @users %>
</ul>

<%= paginate @users %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col">
    <div class="card mx-auto">
      <div class="card-body">
        <h1 class="text-center">Sign up</h1>

        <%= form_for(@user, url: signup_path) do |f| %>
        <%= render "shared/error_messages", object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :user_name %>
        <%= f.text_field :user_name, class: "form-control" %>

        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <%= f.submit "Create my account", class: "btn btn-primary mt-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/password_edit.html.erb
<%= provide(:title, "Update password") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 mx-auto">
    <div class="card text-center">
      <h1 class="font-italic mt-5">Change Password</h1>
      <div class=" card-body font-italic">
        <%= form_for(@user, url: password_edit_user_path(@user)) do |f| %>
        <%= render "shared/error_messages", object: f.object %>

        <%= f.label "Now Password" %>
        <%= f.password_field :password_now, class: "form-control" %>

        <%= f.label :password, "New Password" %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <%= f.submit "Save Change", class: "btn btn-primary font-weight-bolder my-3 w-50" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <ul class="list-unstyled float-left">
    <aside>
      <section class="user_info">
        <li style="font-size: 25px;">
          <%= gravatar_for @user %>
          <%= @user.name %>
          <% if current_user?(@user) %>
          <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-primary btn-sm mt-5" %>
          <% end %>
        </li>
      </section>
      <li>
        <section class="stats mt-3">
          <%= render 'shared/stats' %>
        </section>
      </li>
    </aside>
  </ul>
  <div>
    <%= render 'follow_form' if logged_in? %>
    <% if @user.photos.any? %>
    <h3 class="photo_header mt-3">Photos (<%= @user.photos.count %>)</h3>
    <div class="row">
      <ol class="col3">
        <%= render @photos %>
      </ol>
      <%= paginate @photos %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1 class="font-bolder" style="font-size: 25px;">
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <p><%= link_to "view my profile", @user, class: "btn btn-primary btn-sm" %></p>
      <span>
        <b>Photos:</b> <%= @user.photos.count %>
      </span>
    </section>
    <section class="stats mt-3">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
      <div class="user_avatars">
        <% @users.each do |user| %>
        <%= link_to gravatar_for(user, size: 30), user %>
        <% end %>
      </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
    <ul class="users follow mb-3">
      <%= render @users %>
    </ul>
    <%= paginate @users %>
    <% end %>
  </div>
</div>