config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/terms", to: "static_pages#terms"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get '/auth/:provider/callback', to: 'users#facebook_login', as: :auth_callback
  get '/auth/failure', to: 'users#auth_failure', as: :auth_failure

  resources :users do
    member do
      get :following, :followers, :password_edit
      patch :password_edit, to: "users#update_password"
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :photos, only: [:show, :new, :create, :destroy] do
    resources :comments, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: [:index]
end

app/views/layouts/_footer.html.erb
<footer class="mt-auto">
  <ul class="list-inline d-flex mr-5">
    <% if logged_in? %>
    <li class="list-inline-item mr-auto ml-5">
      <%= link_to "Photo post", new_photo_path, class: "btn btn-info rounded-pill"%>
    </li>
    <% end %>
    <li class="list-inline-item ml-3">
      <%= link_to "Terms of service", terms_path, class: "btn btn-outline-secondary btn-sm" %>
    </li>
    <li class="list-inline-item ml-3"><small class="text-muted">&copy; 2019 INSTAGRAM FROM FACEBOOK</small>
    </li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-white">
  <%= link_to image_tag("header_logo", alt: "home", size: "200x40"), root_path %>
  <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
    aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if logged_in? %>
  <div class="ml-5">
    <%= search_form_for @search, html: { class: "form-row my-auto" } do |f| %>
    <%= f.search_field :name_cont, placeholder: "search...", class: "form-group col-sm-6 my-2 my-lg-0" %>
    <%= f.submit "search", class: "btn btn-outline-dark btn-sm form-group col-sm-4 my-2 ml-3 my-sm-0" %>
    <% end %>
  </div>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul id="header_link" class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item my-auto">
        <%= link_to notifications_path, class: "text-muted" do %>
        <i class="far fa-comment-alt fa-fw"></i>alert
        <% end %>
      </li>
      <li class="nav-item my-auto">
        <%= link_to users_path, class: "text-muted" do %>
        <i class="fas fa-users fa-fw"></i>Users
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Account</a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownId">
          <%= link_to current_user, class: "dropdown-item text-muted" do %>
          <i class="fas fa-portrait fa-fw"></i>Profile
          <% end %>
          <%= link_to edit_user_path(current_user), class: "dropdown-item text-muted" do %>
          <i class="fas fa-user-edit fa-fw"></i>Settings
          <% end %>
          <%= link_to logout_path, method: :delete, class: "dropdown-item text-muted" do %>
          <i class="fas fa-sign-out-alt fa-fw"></i>Log out
          <% end %>
        </div>
      </li>
    </ul>
    <% else %>
    <ul id="header_link" class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item my-auto">
        <%= link_to login_path, class: "text-muted" do %>
        <i class="fas fa-sign-in-alt fa-fw"></i>Log in
        <% end %>
      </li>
    </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/_instagram.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render "layouts/instagram" %>
  <%= render "layouts/shim" %>
</head>

<body>
  <%= render "layouts/header" %>
  <div class="container my-5">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
  <%= debug(params) if Rails.env.development? %>
</body>

</html>